name: Knightbot CI/CD

on:
  schedule:
    - cron: "0 */5 * * *"  # redéploie toutes les 5 h
  workflow_dispatch:       # possibilité de lancer manuellement

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Start Knightbot
        run: node index.js
